import { MigrationInterface, QueryRunner } from "typeorm";

export class UUIDIDtoInt1778516309304 implements MigrationInterface {
    name = 'UUIDIDtoInt1778516309304'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_12ba5f444da355e51efd7a1ff4f"`);
        await queryRunner.query(`ALTER TABLE "credential" DROP CONSTRAINT "PK_3a5169bcd3d5463cefeec78be82"`);
        await queryRunner.query(`ALTER TABLE "credential" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "credential" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "credential" ADD CONSTRAINT "PK_3a5169bcd3d5463cefeec78be82" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_8cbdfb12d62030c7eac59d19dd5"`);
        await queryRunner.query(`ALTER TABLE "point" DROP CONSTRAINT "PK_391f59a9491a08961038a615371"`);
        await queryRunner.query(`ALTER TABLE "point" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "point" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "point" ADD CONSTRAINT "PK_391f59a9491a08961038a615371" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_ce8bf0fc8ab17ac1a3e022a599b"`);
        await queryRunner.query(`ALTER TABLE "streak" DROP CONSTRAINT "PK_dfb968d5a82b523a532bbf7cf70"`);
        await queryRunner.query(`ALTER TABLE "streak" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "streak" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "streak" ADD CONSTRAINT "PK_dfb968d5a82b523a532bbf7cf70" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "flashcard_progress" DROP CONSTRAINT "FK_66180eb31c71965842945612bc5"`);
        await queryRunner.query(`ALTER TABLE "session" DROP CONSTRAINT "FK_30e98e8746699fb9af235410aff"`);
        await queryRunner.query(`ALTER TABLE "session" DROP CONSTRAINT "FK_7c9634a218c5a65aca8dd0b6941"`);
        await queryRunner.query(`ALTER TABLE "session" DROP CONSTRAINT "PK_f55da76ac1c3ac420f444d2ff11"`);
        await queryRunner.query(`ALTER TABLE "session" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "session" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "session" ADD CONSTRAINT "PK_f55da76ac1c3ac420f444d2ff11" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "session" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "session" ADD "user_id" integer`);
        await queryRunner.query(`ALTER TABLE "session" DROP COLUMN "deck_id"`);
        await queryRunner.query(`ALTER TABLE "session" ADD "deck_id" integer`);
        await queryRunner.query(`ALTER TABLE "flashcard_progress" DROP CONSTRAINT "FK_f9a6d30a436783c7458fc747c1b"`);
        await queryRunner.query(`ALTER TABLE "flashcard_progress" DROP CONSTRAINT "FK_ca1acac4480a1495f1b51a45033"`);
        await queryRunner.query(`ALTER TABLE "flashcard_progress" DROP CONSTRAINT "FK_72bfaa1d2686fa0bc5009026649"`);
        await queryRunner.query(`ALTER TABLE "flashcard_progress" DROP CONSTRAINT "PK_2d6db376b5526cbeb9b9bbc1448"`);
        await queryRunner.query(`ALTER TABLE "flashcard_progress" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "flashcard_progress" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "flashcard_progress" ADD CONSTRAINT "PK_2d6db376b5526cbeb9b9bbc1448" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "flashcard_progress" DROP COLUMN "sessionId"`);
        await queryRunner.query(`ALTER TABLE "flashcard_progress" ADD "sessionId" integer`);
        await queryRunner.query(`ALTER TABLE "flashcard_progress" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "flashcard_progress" ADD "user_id" integer`);
        await queryRunner.query(`ALTER TABLE "flashcard_progress" DROP COLUMN "flashcard_id"`);
        await queryRunner.query(`ALTER TABLE "flashcard_progress" ADD "flashcard_id" integer`);
        await queryRunner.query(`ALTER TABLE "flashcard_progress" DROP COLUMN "deck_id"`);
        await queryRunner.query(`ALTER TABLE "flashcard_progress" ADD "deck_id" integer`);
        await queryRunner.query(`ALTER TABLE "flashcard" DROP CONSTRAINT "FK_85ba35183ea3d7b22dc6514b581"`);
        await queryRunner.query(`ALTER TABLE "flashcard" DROP CONSTRAINT "FK_d3612c2a1e9cae3c380b4d669a3"`);
        await queryRunner.query(`ALTER TABLE "flashcard" DROP CONSTRAINT "PK_e0aba0501d3bc532951efc9f791"`);
        await queryRunner.query(`ALTER TABLE "flashcard" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "flashcard" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "flashcard" ADD CONSTRAINT "PK_e0aba0501d3bc532951efc9f791" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "flashcard" DROP COLUMN "deck_id"`);
        await queryRunner.query(`ALTER TABLE "flashcard" ADD "deck_id" integer`);
        await queryRunner.query(`ALTER TABLE "flashcard" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "flashcard" ADD "user_id" integer`);
        await queryRunner.query(`ALTER TABLE "user_saved_collection" DROP CONSTRAINT "FK_a1e2661f6f7c069c7454e382701"`);
        await queryRunner.query(`ALTER TABLE "user_saved_collection" DROP CONSTRAINT "FK_e1259ba1cc25f180460cbc80370"`);
        await queryRunner.query(`ALTER TABLE "user_saved_collection" DROP CONSTRAINT "PK_0a8c62dbd5b0cdf1c6f86f81c3f"`);
        await queryRunner.query(`ALTER TABLE "user_saved_collection" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "user_saved_collection" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_saved_collection" ADD CONSTRAINT "PK_0a8c62dbd5b0cdf1c6f86f81c3f" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "user_saved_collection" DROP COLUMN "collectionId"`);
        await queryRunner.query(`ALTER TABLE "user_saved_collection" ADD "collectionId" integer`);
        await queryRunner.query(`ALTER TABLE "user_saved_collection" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "user_saved_collection" ADD "userId" integer`);
        await queryRunner.query(`ALTER TABLE "collection_deck" DROP CONSTRAINT "FK_a9804f0fb5ca233f9168f662af7"`);
        await queryRunner.query(`ALTER TABLE "collection" DROP CONSTRAINT "FK_4f925485b013b52e32f43d430f6"`);
        await queryRunner.query(`ALTER TABLE "collection" DROP CONSTRAINT "PK_ad3f485bbc99d875491f44d7c85"`);
        await queryRunner.query(`ALTER TABLE "collection" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "collection" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "collection" ADD CONSTRAINT "PK_ad3f485bbc99d875491f44d7c85" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "collection" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "collection" ADD "user_id" integer`);
        await queryRunner.query(`ALTER TABLE "collection_deck" DROP CONSTRAINT "FK_a898e2ac3709a71fe4872651379"`);
        await queryRunner.query(`ALTER TABLE "collection_deck" DROP CONSTRAINT "FK_5dcc9e80fd2b3c181a27dff9137"`);
        await queryRunner.query(`ALTER TABLE "collection_deck" DROP CONSTRAINT "PK_62ab700b841b2eb25aaea25ae96"`);
        await queryRunner.query(`ALTER TABLE "collection_deck" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "collection_deck" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "collection_deck" ADD CONSTRAINT "PK_62ab700b841b2eb25aaea25ae96" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "collection_deck" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "collection_deck" ADD "user_id" integer`);
        await queryRunner.query(`ALTER TABLE "collection_deck" DROP COLUMN "collection_id"`);
        await queryRunner.query(`ALTER TABLE "collection_deck" ADD "collection_id" integer`);
        await queryRunner.query(`ALTER TABLE "collection_deck" DROP COLUMN "deck_id"`);
        await queryRunner.query(`ALTER TABLE "collection_deck" ADD "deck_id" integer`);
        await queryRunner.query(`ALTER TABLE "user_saved_deck" DROP CONSTRAINT "FK_e634b08c0f21d55fc2c9c85416f"`);
        await queryRunner.query(`ALTER TABLE "user_saved_deck" DROP CONSTRAINT "FK_3eb05f9fa305ea8109b19e786c2"`);
        await queryRunner.query(`ALTER TABLE "user_saved_deck" DROP CONSTRAINT "PK_63fab6867351be3effad66635a2"`);
        await queryRunner.query(`ALTER TABLE "user_saved_deck" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "user_saved_deck" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_saved_deck" ADD CONSTRAINT "PK_63fab6867351be3effad66635a2" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "user_saved_deck" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "user_saved_deck" ADD "user_id" integer`);
        await queryRunner.query(`ALTER TABLE "user_saved_deck" DROP COLUMN "deck_id"`);
        await queryRunner.query(`ALTER TABLE "user_saved_deck" ADD "deck_id" integer`);
        await queryRunner.query(`ALTER TABLE "deck" DROP CONSTRAINT "FK_ed0def52a370eb424db27fc2b5b"`);
        await queryRunner.query(`ALTER TABLE "deck" DROP CONSTRAINT "PK_99f8010303acab0edf8e1df24f9"`);
        await queryRunner.query(`ALTER TABLE "deck" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "deck" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "deck" ADD CONSTRAINT "PK_99f8010303acab0edf8e1df24f9" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "deck" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "deck" ADD "user_id" integer`);
        await queryRunner.query(`ALTER TABLE "message" DROP CONSTRAINT "FK_7cf4a4df1f2627f72bf6231635f"`);
        await queryRunner.query(`ALTER TABLE "conversation" DROP CONSTRAINT "FK_c308b1cd542522bb66430fa860a"`);
        await queryRunner.query(`ALTER TABLE "conversation" DROP CONSTRAINT "PK_864528ec4274360a40f66c29845"`);
        await queryRunner.query(`ALTER TABLE "conversation" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "conversation" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "conversation" ADD CONSTRAINT "PK_864528ec4274360a40f66c29845" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "conversation" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "conversation" ADD "userId" integer`);
        await queryRunner.query(`ALTER TABLE "message" DROP CONSTRAINT "FK_446251f8ceb2132af01b68eb593"`);
        await queryRunner.query(`ALTER TABLE "message" DROP CONSTRAINT "PK_ba01f0a3e0123651915008bc578"`);
        await queryRunner.query(`ALTER TABLE "message" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "message" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "message" ADD CONSTRAINT "PK_ba01f0a3e0123651915008bc578" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "message" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "message" ADD "userId" integer`);
        await queryRunner.query(`ALTER TABLE "message" DROP COLUMN "conversationId"`);
        await queryRunner.query(`ALTER TABLE "message" ADD "conversationId" integer`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "PK_cace4a159ff9f2512dd42373760"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "user" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "REL_12ba5f444da355e51efd7a1ff4"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "credential_id"`);
        await queryRunner.query(`ALTER TABLE "user" ADD "credential_id" integer`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "UQ_12ba5f444da355e51efd7a1ff4f" UNIQUE ("credential_id")`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "REL_8cbdfb12d62030c7eac59d19dd"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "point_id"`);
        await queryRunner.query(`ALTER TABLE "user" ADD "point_id" integer`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "UQ_8cbdfb12d62030c7eac59d19dd5" UNIQUE ("point_id")`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "REL_ce8bf0fc8ab17ac1a3e022a599"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "streak_id"`);
        await queryRunner.query(`ALTER TABLE "user" ADD "streak_id" integer`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "UQ_ce8bf0fc8ab17ac1a3e022a599b" UNIQUE ("streak_id")`);
        await queryRunner.query(`ALTER TABLE "session" ADD CONSTRAINT "FK_30e98e8746699fb9af235410aff" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "session" ADD CONSTRAINT "FK_7c9634a218c5a65aca8dd0b6941" FOREIGN KEY ("deck_id") REFERENCES "deck"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "flashcard_progress" ADD CONSTRAINT "FK_66180eb31c71965842945612bc5" FOREIGN KEY ("sessionId") REFERENCES "session"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "flashcard_progress" ADD CONSTRAINT "FK_f9a6d30a436783c7458fc747c1b" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "flashcard_progress" ADD CONSTRAINT "FK_ca1acac4480a1495f1b51a45033" FOREIGN KEY ("flashcard_id") REFERENCES "flashcard"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "flashcard_progress" ADD CONSTRAINT "FK_72bfaa1d2686fa0bc5009026649" FOREIGN KEY ("deck_id") REFERENCES "deck"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "flashcard" ADD CONSTRAINT "FK_85ba35183ea3d7b22dc6514b581" FOREIGN KEY ("deck_id") REFERENCES "deck"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "flashcard" ADD CONSTRAINT "FK_d3612c2a1e9cae3c380b4d669a3" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_saved_collection" ADD CONSTRAINT "FK_a1e2661f6f7c069c7454e382701" FOREIGN KEY ("collectionId") REFERENCES "collection"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_saved_collection" ADD CONSTRAINT "FK_e1259ba1cc25f180460cbc80370" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "collection" ADD CONSTRAINT "FK_4f925485b013b52e32f43d430f6" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "collection_deck" ADD CONSTRAINT "FK_a898e2ac3709a71fe4872651379" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "collection_deck" ADD CONSTRAINT "FK_a9804f0fb5ca233f9168f662af7" FOREIGN KEY ("collection_id") REFERENCES "collection"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "collection_deck" ADD CONSTRAINT "FK_5dcc9e80fd2b3c181a27dff9137" FOREIGN KEY ("deck_id") REFERENCES "deck"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_saved_deck" ADD CONSTRAINT "FK_e634b08c0f21d55fc2c9c85416f" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_saved_deck" ADD CONSTRAINT "FK_3eb05f9fa305ea8109b19e786c2" FOREIGN KEY ("deck_id") REFERENCES "deck"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "deck" ADD CONSTRAINT "FK_ed0def52a370eb424db27fc2b5b" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversation" ADD CONSTRAINT "FK_c308b1cd542522bb66430fa860a" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "message" ADD CONSTRAINT "FK_446251f8ceb2132af01b68eb593" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "message" ADD CONSTRAINT "FK_7cf4a4df1f2627f72bf6231635f" FOREIGN KEY ("conversationId") REFERENCES "conversation"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_12ba5f444da355e51efd7a1ff4f" FOREIGN KEY ("credential_id") REFERENCES "credential"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_8cbdfb12d62030c7eac59d19dd5" FOREIGN KEY ("point_id") REFERENCES "point"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_ce8bf0fc8ab17ac1a3e022a599b" FOREIGN KEY ("streak_id") REFERENCES "streak"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_ce8bf0fc8ab17ac1a3e022a599b"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_8cbdfb12d62030c7eac59d19dd5"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_12ba5f444da355e51efd7a1ff4f"`);
        await queryRunner.query(`ALTER TABLE "message" DROP CONSTRAINT "FK_7cf4a4df1f2627f72bf6231635f"`);
        await queryRunner.query(`ALTER TABLE "message" DROP CONSTRAINT "FK_446251f8ceb2132af01b68eb593"`);
        await queryRunner.query(`ALTER TABLE "conversation" DROP CONSTRAINT "FK_c308b1cd542522bb66430fa860a"`);
        await queryRunner.query(`ALTER TABLE "deck" DROP CONSTRAINT "FK_ed0def52a370eb424db27fc2b5b"`);
        await queryRunner.query(`ALTER TABLE "user_saved_deck" DROP CONSTRAINT "FK_3eb05f9fa305ea8109b19e786c2"`);
        await queryRunner.query(`ALTER TABLE "user_saved_deck" DROP CONSTRAINT "FK_e634b08c0f21d55fc2c9c85416f"`);
        await queryRunner.query(`ALTER TABLE "collection_deck" DROP CONSTRAINT "FK_5dcc9e80fd2b3c181a27dff9137"`);
        await queryRunner.query(`ALTER TABLE "collection_deck" DROP CONSTRAINT "FK_a9804f0fb5ca233f9168f662af7"`);
        await queryRunner.query(`ALTER TABLE "collection_deck" DROP CONSTRAINT "FK_a898e2ac3709a71fe4872651379"`);
        await queryRunner.query(`ALTER TABLE "collection" DROP CONSTRAINT "FK_4f925485b013b52e32f43d430f6"`);
        await queryRunner.query(`ALTER TABLE "user_saved_collection" DROP CONSTRAINT "FK_e1259ba1cc25f180460cbc80370"`);
        await queryRunner.query(`ALTER TABLE "user_saved_collection" DROP CONSTRAINT "FK_a1e2661f6f7c069c7454e382701"`);
        await queryRunner.query(`ALTER TABLE "flashcard" DROP CONSTRAINT "FK_d3612c2a1e9cae3c380b4d669a3"`);
        await queryRunner.query(`ALTER TABLE "flashcard" DROP CONSTRAINT "FK_85ba35183ea3d7b22dc6514b581"`);
        await queryRunner.query(`ALTER TABLE "flashcard_progress" DROP CONSTRAINT "FK_72bfaa1d2686fa0bc5009026649"`);
        await queryRunner.query(`ALTER TABLE "flashcard_progress" DROP CONSTRAINT "FK_ca1acac4480a1495f1b51a45033"`);
        await queryRunner.query(`ALTER TABLE "flashcard_progress" DROP CONSTRAINT "FK_f9a6d30a436783c7458fc747c1b"`);
        await queryRunner.query(`ALTER TABLE "flashcard_progress" DROP CONSTRAINT "FK_66180eb31c71965842945612bc5"`);
        await queryRunner.query(`ALTER TABLE "session" DROP CONSTRAINT "FK_7c9634a218c5a65aca8dd0b6941"`);
        await queryRunner.query(`ALTER TABLE "session" DROP CONSTRAINT "FK_30e98e8746699fb9af235410aff"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "UQ_ce8bf0fc8ab17ac1a3e022a599b"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "streak_id"`);
        await queryRunner.query(`ALTER TABLE "user" ADD "streak_id" uuid`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "REL_ce8bf0fc8ab17ac1a3e022a599" UNIQUE ("streak_id")`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "UQ_8cbdfb12d62030c7eac59d19dd5"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "point_id"`);
        await queryRunner.query(`ALTER TABLE "user" ADD "point_id" uuid`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "REL_8cbdfb12d62030c7eac59d19dd" UNIQUE ("point_id")`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "UQ_12ba5f444da355e51efd7a1ff4f"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "credential_id"`);
        await queryRunner.query(`ALTER TABLE "user" ADD "credential_id" uuid`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "REL_12ba5f444da355e51efd7a1ff4" UNIQUE ("credential_id")`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "PK_cace4a159ff9f2512dd42373760"`);
        await queryRunner.query(`ALTER TABLE "user" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "user" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "message" DROP COLUMN "conversationId"`);
        await queryRunner.query(`ALTER TABLE "message" ADD "conversationId" uuid`);
        await queryRunner.query(`ALTER TABLE "message" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "message" ADD "userId" uuid`);
        await queryRunner.query(`ALTER TABLE "message" DROP CONSTRAINT "PK_ba01f0a3e0123651915008bc578"`);
        await queryRunner.query(`ALTER TABLE "message" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "message" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "message" ADD CONSTRAINT "PK_ba01f0a3e0123651915008bc578" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "message" ADD CONSTRAINT "FK_446251f8ceb2132af01b68eb593" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversation" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "conversation" ADD "userId" uuid`);
        await queryRunner.query(`ALTER TABLE "conversation" DROP CONSTRAINT "PK_864528ec4274360a40f66c29845"`);
        await queryRunner.query(`ALTER TABLE "conversation" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "conversation" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "conversation" ADD CONSTRAINT "PK_864528ec4274360a40f66c29845" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "conversation" ADD CONSTRAINT "FK_c308b1cd542522bb66430fa860a" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "message" ADD CONSTRAINT "FK_7cf4a4df1f2627f72bf6231635f" FOREIGN KEY ("conversationId") REFERENCES "conversation"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "deck" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "deck" ADD "user_id" uuid`);
        await queryRunner.query(`ALTER TABLE "deck" DROP CONSTRAINT "PK_99f8010303acab0edf8e1df24f9"`);
        await queryRunner.query(`ALTER TABLE "deck" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "deck" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "deck" ADD CONSTRAINT "PK_99f8010303acab0edf8e1df24f9" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "deck" ADD CONSTRAINT "FK_ed0def52a370eb424db27fc2b5b" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_saved_deck" DROP COLUMN "deck_id"`);
        await queryRunner.query(`ALTER TABLE "user_saved_deck" ADD "deck_id" uuid`);
        await queryRunner.query(`ALTER TABLE "user_saved_deck" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "user_saved_deck" ADD "user_id" uuid`);
        await queryRunner.query(`ALTER TABLE "user_saved_deck" DROP CONSTRAINT "PK_63fab6867351be3effad66635a2"`);
        await queryRunner.query(`ALTER TABLE "user_saved_deck" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "user_saved_deck" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "user_saved_deck" ADD CONSTRAINT "PK_63fab6867351be3effad66635a2" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "user_saved_deck" ADD CONSTRAINT "FK_3eb05f9fa305ea8109b19e786c2" FOREIGN KEY ("deck_id") REFERENCES "deck"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_saved_deck" ADD CONSTRAINT "FK_e634b08c0f21d55fc2c9c85416f" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "collection_deck" DROP COLUMN "deck_id"`);
        await queryRunner.query(`ALTER TABLE "collection_deck" ADD "deck_id" uuid`);
        await queryRunner.query(`ALTER TABLE "collection_deck" DROP COLUMN "collection_id"`);
        await queryRunner.query(`ALTER TABLE "collection_deck" ADD "collection_id" uuid`);
        await queryRunner.query(`ALTER TABLE "collection_deck" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "collection_deck" ADD "user_id" uuid`);
        await queryRunner.query(`ALTER TABLE "collection_deck" DROP CONSTRAINT "PK_62ab700b841b2eb25aaea25ae96"`);
        await queryRunner.query(`ALTER TABLE "collection_deck" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "collection_deck" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "collection_deck" ADD CONSTRAINT "PK_62ab700b841b2eb25aaea25ae96" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "collection_deck" ADD CONSTRAINT "FK_5dcc9e80fd2b3c181a27dff9137" FOREIGN KEY ("deck_id") REFERENCES "deck"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "collection_deck" ADD CONSTRAINT "FK_a898e2ac3709a71fe4872651379" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "collection" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "collection" ADD "user_id" uuid`);
        await queryRunner.query(`ALTER TABLE "collection" DROP CONSTRAINT "PK_ad3f485bbc99d875491f44d7c85"`);
        await queryRunner.query(`ALTER TABLE "collection" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "collection" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "collection" ADD CONSTRAINT "PK_ad3f485bbc99d875491f44d7c85" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "collection" ADD CONSTRAINT "FK_4f925485b013b52e32f43d430f6" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "collection_deck" ADD CONSTRAINT "FK_a9804f0fb5ca233f9168f662af7" FOREIGN KEY ("collection_id") REFERENCES "collection"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_saved_collection" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "user_saved_collection" ADD "userId" uuid`);
        await queryRunner.query(`ALTER TABLE "user_saved_collection" DROP COLUMN "collectionId"`);
        await queryRunner.query(`ALTER TABLE "user_saved_collection" ADD "collectionId" uuid`);
        await queryRunner.query(`ALTER TABLE "user_saved_collection" DROP CONSTRAINT "PK_0a8c62dbd5b0cdf1c6f86f81c3f"`);
        await queryRunner.query(`ALTER TABLE "user_saved_collection" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "user_saved_collection" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "user_saved_collection" ADD CONSTRAINT "PK_0a8c62dbd5b0cdf1c6f86f81c3f" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "user_saved_collection" ADD CONSTRAINT "FK_e1259ba1cc25f180460cbc80370" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_saved_collection" ADD CONSTRAINT "FK_a1e2661f6f7c069c7454e382701" FOREIGN KEY ("collectionId") REFERENCES "collection"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "flashcard" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "flashcard" ADD "user_id" uuid`);
        await queryRunner.query(`ALTER TABLE "flashcard" DROP COLUMN "deck_id"`);
        await queryRunner.query(`ALTER TABLE "flashcard" ADD "deck_id" uuid`);
        await queryRunner.query(`ALTER TABLE "flashcard" DROP CONSTRAINT "PK_e0aba0501d3bc532951efc9f791"`);
        await queryRunner.query(`ALTER TABLE "flashcard" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "flashcard" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "flashcard" ADD CONSTRAINT "PK_e0aba0501d3bc532951efc9f791" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "flashcard" ADD CONSTRAINT "FK_d3612c2a1e9cae3c380b4d669a3" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "flashcard" ADD CONSTRAINT "FK_85ba35183ea3d7b22dc6514b581" FOREIGN KEY ("deck_id") REFERENCES "deck"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "flashcard_progress" DROP COLUMN "deck_id"`);
        await queryRunner.query(`ALTER TABLE "flashcard_progress" ADD "deck_id" uuid`);
        await queryRunner.query(`ALTER TABLE "flashcard_progress" DROP COLUMN "flashcard_id"`);
        await queryRunner.query(`ALTER TABLE "flashcard_progress" ADD "flashcard_id" uuid`);
        await queryRunner.query(`ALTER TABLE "flashcard_progress" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "flashcard_progress" ADD "user_id" uuid`);
        await queryRunner.query(`ALTER TABLE "flashcard_progress" DROP COLUMN "sessionId"`);
        await queryRunner.query(`ALTER TABLE "flashcard_progress" ADD "sessionId" uuid`);
        await queryRunner.query(`ALTER TABLE "flashcard_progress" DROP CONSTRAINT "PK_2d6db376b5526cbeb9b9bbc1448"`);
        await queryRunner.query(`ALTER TABLE "flashcard_progress" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "flashcard_progress" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "flashcard_progress" ADD CONSTRAINT "PK_2d6db376b5526cbeb9b9bbc1448" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "flashcard_progress" ADD CONSTRAINT "FK_72bfaa1d2686fa0bc5009026649" FOREIGN KEY ("deck_id") REFERENCES "deck"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "flashcard_progress" ADD CONSTRAINT "FK_ca1acac4480a1495f1b51a45033" FOREIGN KEY ("flashcard_id") REFERENCES "flashcard"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "flashcard_progress" ADD CONSTRAINT "FK_f9a6d30a436783c7458fc747c1b" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "session" DROP COLUMN "deck_id"`);
        await queryRunner.query(`ALTER TABLE "session" ADD "deck_id" uuid`);
        await queryRunner.query(`ALTER TABLE "session" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "session" ADD "user_id" uuid`);
        await queryRunner.query(`ALTER TABLE "session" DROP CONSTRAINT "PK_f55da76ac1c3ac420f444d2ff11"`);
        await queryRunner.query(`ALTER TABLE "session" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "session" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "session" ADD CONSTRAINT "PK_f55da76ac1c3ac420f444d2ff11" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "session" ADD CONSTRAINT "FK_7c9634a218c5a65aca8dd0b6941" FOREIGN KEY ("deck_id") REFERENCES "deck"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "session" ADD CONSTRAINT "FK_30e98e8746699fb9af235410aff" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "flashcard_progress" ADD CONSTRAINT "FK_66180eb31c71965842945612bc5" FOREIGN KEY ("sessionId") REFERENCES "session"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "streak" DROP CONSTRAINT "PK_dfb968d5a82b523a532bbf7cf70"`);
        await queryRunner.query(`ALTER TABLE "streak" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "streak" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "streak" ADD CONSTRAINT "PK_dfb968d5a82b523a532bbf7cf70" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_ce8bf0fc8ab17ac1a3e022a599b" FOREIGN KEY ("streak_id") REFERENCES "streak"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "point" DROP CONSTRAINT "PK_391f59a9491a08961038a615371"`);
        await queryRunner.query(`ALTER TABLE "point" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "point" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "point" ADD CONSTRAINT "PK_391f59a9491a08961038a615371" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_8cbdfb12d62030c7eac59d19dd5" FOREIGN KEY ("point_id") REFERENCES "point"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credential" DROP CONSTRAINT "PK_3a5169bcd3d5463cefeec78be82"`);
        await queryRunner.query(`ALTER TABLE "credential" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "credential" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "credential" ADD CONSTRAINT "PK_3a5169bcd3d5463cefeec78be82" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_12ba5f444da355e51efd7a1ff4f" FOREIGN KEY ("credential_id") REFERENCES "credential"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
