"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _avatar from './avatar.bones.json'
import _nickname from './nickname.bones.json'
import _username from './username.bones.json'
import _card from './card.bones.json'
import _profile_nickname from './profile-nickname.bones.json'
import _profile_username from './profile-username.bones.json'
import _accuracy from './accuracy.bones.json'
import _button from './button.bones.json'
import _deck from './deck.bones.json'
import _points from './points.bones.json'
import _rank from './rank.bones.json'
import _search_bar from './search-bar.bones.json'
import _settings_avatar_section from './settings-avatar-section.bones.json'
import _settings_name_section from './settings-name-section.bones.json'
import _settings_preferences_section from './settings-preferences-section.bones.json'
import _settings_security_section from './settings-security-section.bones.json'
import _stat_card from './stat-card.bones.json'
import _username_nickname from './username-nickname.bones.json'

registerBones({
  "avatar": _avatar,
  "nickname": _nickname,
  "username": _username,
  "card": _card,
  "profile-nickname": _profile_nickname,
  "profile-username": _profile_username,
  "accuracy": _accuracy,
  "button": _button,
  "deck": _deck,
  "points": _points,
  "rank": _rank,
  "search-bar": _search_bar,
  "settings-avatar-section": _settings_avatar_section,
  "settings-name-section": _settings_name_section,
  "settings-preferences-section": _settings_preferences_section,
  "settings-security-section": _settings_security_section,
  "stat-card": _stat_card,
  "username-nickname": _username_nickname,
})
